name: Java CI with Maven

on:
  push:
    branches: [ "master" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: find settings.xml file
        run: mvn install:install-file -Dfile=/home/runner/work/automationproject/automationproject/src/main/resources/automation-framework-1.0.31.jar -DgroupId=com.ey.framework -DartifactId=automation-framework -Dversion=1.0.31 -Dpackaging=jar -DgeneratePom=true
      - name: Build with Maven
        run: mvn clean test -Pselenium-test --file pom.xml
      - name: Download target for results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: target
          path: /home/runner/work/automationproject/automationproject/target
